os: Visual Studio 2015

environment:
  matrix:
    - channel: nightly
      target: i686-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin

build_script:
  - cargo build --release --target=%TARGET%

test_script:
  - cargo test
