os: Visual Studio 2015

branches:
  only:
    - master
    - "/^v[0-9].*$/"

environment:
  matrix:
    - CHANNEL: stable
      TARGET: i686-pc-windows-msvc
    - CHANNEL: stable
      TARGET: x86_64-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %CHANNEL% --default-host %TARGET%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin

build_script:
  - cargo build --release --target=%TARGET%

test_script:
  - cargo test
  - mkdir logian-%APPVEYOR_REPO_TAG_NAME%-%TARGET%
  - copy target\%TARGET%\release\logian.exe logian-%APPVEYOR_REPO_TAG_NAME%-%TARGET%\logian.exe
  - xcopy template logian-%APPVEYOR_REPO_TAG_NAME%-%TARGET%\template /I /E /Y /D
  - xcopy plugin logian-%APPVEYOR_REPO_TAG_NAME%-%TARGET%\plugin /I /E /Y /D
  - 7z a logian-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip logian-%APPVEYOR_REPO_TAG_NAME%-%TARGET%
  - appveyor PushArtifact logian-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip

artifacts:
  - path: logian-*.zip
    name: Releases

deploy:
  provider: GitHub
  auth_token:
    secure: "dhtE2Pulq8NfxuIL4jZfFQLwxIiwAnM04Br9WvUPmlzzLS0sQc5iFUPPtGr+P8xm"
  artifact: /logian-.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

