[package]
name = "logian"
version = "0.1.0"
authors = ["naokirin <naoki.rin186@gmail.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
tera = "*"
glob = "*"
docopt = "*"
docopt_macros = "*"
fs_extra = "*"

[[bench]]
name = "bench"
path = "benches/bench.rs"
